CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

CREATE TABLE threads (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    thread jsonb NULL,
    board jsonb NULL,
    is_pinned boolean NOT NULL,
    is_locked boolean NOT NULL,
    is_deleted boolean NOT NULL,
    type integer NOT NULL,
    last_post_no integer NOT NULL,
    last_post_page integer NOT NULL,
    created timestamp with time zone NOT NULL,
    total_posts integer NOT NULL,
    total_view integer NOT NULL,
    creator jsonb NULL,
    comments integer[] NULL,
    CONSTRAINT pk_threads PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20230422112523_Initial', '7.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE threads RENAME COLUMN comments TO posts;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20230426200040_minor change in thread schema', '7.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE threads DROP COLUMN posts;

CREATE TABLE posts (
    id text NOT NULL,
    is_comment boolean NOT NULL,
    is_deleted boolean NOT NULL,
    is_mod_comment boolean NOT NULL,
    post_no integer NOT NULL,
    creator jsonb NULL,
    is_edited boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    content text NULL,
    thread_id integer NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (id),
    CONSTRAINT fk_posts_threads_thread_id FOREIGN KEY (thread_id) REFERENCES threads (id) ON DELETE CASCADE
);

CREATE INDEX ix_posts_thread_id ON posts (thread_id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20230427121144_add post entity', '7.0.3');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20230428153019_idk', '7.0.3');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20230516162526_stopped using settings.json', '7.0.3');

COMMIT;

START TRANSACTION;

CREATE INDEX ix_threads_created ON threads (created DESC);

CREATE INDEX ix_posts_created ON posts (created DESC);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20241223211333_index on thread.created and post.created', '7.0.3');

COMMIT;

START TRANSACTION;

CREATE INDEX ix_posts_creator_text ON posts ((creator->>'Text'));

CREATE INDEX ix_threads_creator_text ON threads ((creator->>'Text'));

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20241223213958_index on thread.creator.text and post.creator.text', '7.0.3');

COMMIT;

